// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package languagecodes.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the LanguageCodes module
	public static void aCT_LanguageCodes_DeleteAll(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("LanguageCodes.ACT_LanguageCodes_DeleteAll").withParams(params).execute(context);
	}
	public static void aCT_LanguageCodes_Update(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("LanguageCodes.ACT_LanguageCodes_Update").withParams(params).execute(context);
	}
	public static languagecodes.proxies.LanguageCode dS_LanguageCode_by_Alpha3_b(IContext context, java.lang.String _alpha3_b)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("alpha3_b", _alpha3_b);
		IMendixObject result = (IMendixObject)Core.microflowCall("LanguageCodes.DS_LanguageCode_by_Alpha3_b").withParams(params).execute(context);
		return result == null ? null : languagecodes.proxies.LanguageCode.initialize(context, result);
	}
}