// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package languagecodes.proxies;

public class LanguageCode
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject languageCodeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "LanguageCodes.LanguageCode";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		English("English"),
		French("French"),
		Alpha2("Alpha2"),
		Alpha3_t("Alpha3_t"),
		Alpha3_b("Alpha3_b");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public LanguageCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "LanguageCodes.LanguageCode"));
	}

	protected LanguageCode(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject languageCodeMendixObject)
	{
		if (languageCodeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("LanguageCodes.LanguageCode", languageCodeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a LanguageCodes.LanguageCode");

		this.languageCodeMendixObject = languageCodeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'LanguageCode.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static languagecodes.proxies.LanguageCode initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return languagecodes.proxies.LanguageCode.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static languagecodes.proxies.LanguageCode initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new languagecodes.proxies.LanguageCode(context, mendixObject);
	}

	public static languagecodes.proxies.LanguageCode load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return languagecodes.proxies.LanguageCode.initialize(context, mendixObject);
	}

	public static java.util.List<languagecodes.proxies.LanguageCode> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<languagecodes.proxies.LanguageCode> result = new java.util.ArrayList<languagecodes.proxies.LanguageCode>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//LanguageCodes.LanguageCode" + xpathConstraint))
			result.add(languagecodes.proxies.LanguageCode.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of English
	 */
	public final java.lang.String getEnglish()
	{
		return getEnglish(getContext());
	}

	/**
	 * @param context
	 * @return value of English
	 */
	public final java.lang.String getEnglish(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.English.toString());
	}

	/**
	 * Set value of English
	 * @param english
	 */
	public final void setEnglish(java.lang.String english)
	{
		setEnglish(getContext(), english);
	}

	/**
	 * Set value of English
	 * @param context
	 * @param english
	 */
	public final void setEnglish(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String english)
	{
		getMendixObject().setValue(context, MemberNames.English.toString(), english);
	}

	/**
	 * @return value of French
	 */
	public final java.lang.String getFrench()
	{
		return getFrench(getContext());
	}

	/**
	 * @param context
	 * @return value of French
	 */
	public final java.lang.String getFrench(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.French.toString());
	}

	/**
	 * Set value of French
	 * @param french
	 */
	public final void setFrench(java.lang.String french)
	{
		setFrench(getContext(), french);
	}

	/**
	 * Set value of French
	 * @param context
	 * @param french
	 */
	public final void setFrench(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String french)
	{
		getMendixObject().setValue(context, MemberNames.French.toString(), french);
	}

	/**
	 * @return value of Alpha2
	 */
	public final java.lang.String getAlpha2()
	{
		return getAlpha2(getContext());
	}

	/**
	 * @param context
	 * @return value of Alpha2
	 */
	public final java.lang.String getAlpha2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Alpha2.toString());
	}

	/**
	 * Set value of Alpha2
	 * @param alpha2
	 */
	public final void setAlpha2(java.lang.String alpha2)
	{
		setAlpha2(getContext(), alpha2);
	}

	/**
	 * Set value of Alpha2
	 * @param context
	 * @param alpha2
	 */
	public final void setAlpha2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String alpha2)
	{
		getMendixObject().setValue(context, MemberNames.Alpha2.toString(), alpha2);
	}

	/**
	 * @return value of Alpha3_t
	 */
	public final java.lang.String getAlpha3_t()
	{
		return getAlpha3_t(getContext());
	}

	/**
	 * @param context
	 * @return value of Alpha3_t
	 */
	public final java.lang.String getAlpha3_t(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Alpha3_t.toString());
	}

	/**
	 * Set value of Alpha3_t
	 * @param alpha3_t
	 */
	public final void setAlpha3_t(java.lang.String alpha3_t)
	{
		setAlpha3_t(getContext(), alpha3_t);
	}

	/**
	 * Set value of Alpha3_t
	 * @param context
	 * @param alpha3_t
	 */
	public final void setAlpha3_t(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String alpha3_t)
	{
		getMendixObject().setValue(context, MemberNames.Alpha3_t.toString(), alpha3_t);
	}

	/**
	 * @return value of Alpha3_b
	 */
	public final java.lang.String getAlpha3_b()
	{
		return getAlpha3_b(getContext());
	}

	/**
	 * @param context
	 * @return value of Alpha3_b
	 */
	public final java.lang.String getAlpha3_b(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Alpha3_b.toString());
	}

	/**
	 * Set value of Alpha3_b
	 * @param alpha3_b
	 */
	public final void setAlpha3_b(java.lang.String alpha3_b)
	{
		setAlpha3_b(getContext(), alpha3_b);
	}

	/**
	 * Set value of Alpha3_b
	 * @param context
	 * @param alpha3_b
	 */
	public final void setAlpha3_b(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String alpha3_b)
	{
		getMendixObject().setValue(context, MemberNames.Alpha3_b.toString(), alpha3_b);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return languageCodeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final languagecodes.proxies.LanguageCode that = (languagecodes.proxies.LanguageCode) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "LanguageCodes.LanguageCode";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
